spring:
  datasource:
    #url: jdbc:h2:mem:testdb
    #url: jdbc:postgresql://localhost:5432/films
    #username: usr
    #password: pwd
    #driver-class-name: org.postgresql.Driver

    url: jdbc:sqlserver://localhost\SQLEXPRESS:13414;databaseName=films;trustServerCertificate=true;
    userName: ${sql-user-name}
    password: ${sql-user-pass}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    initialization-mode: never

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    clean-on-validation-error: true

app:
  #repositoryMode: jdbc(n+1)
  #repositoryMode: jdbc(multiply)
  #repositoryMode: jdbc(gibrid)
  #repositoryMode: jpa(n+1)
  #repositoryMode: jpa(multiply)
  #repositoryMode: jpa(gibrid)